# Generated by Django 5.2.3 on 2025-06-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='nome_medico',
            field=models.CharField(default='Liamara Correa', max_length=100),
        ),
    ]
